app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 1m

  api:
    bot:
      base-url: http://${BOT_HOST}:${BOT_PORT}
    github:
      base-url: https://api.github.com
      access-token: ${GITHUB_ACCESS_TOKEN}
    stackoverflow:
      base-url: https://api.stackexchange.com

spring:
  devtools:
    restart:
      enabled: false
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

server:
  port: ${SCRAPPER_PORT}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
