app:
  telegram-token: ${TELEGRAM-TOKEN}
  scrapper-base-url: http://${SCRAPPER_HOST}:${SCRAPPER_PORT}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: ${BOT_PORT}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
